export const FETCH_REDDIT_POSTS_REQUEST = 'FETCH_REDDIT_POSTS_REQUEST';
export const FETCH_REDDIT_POSTS_SUCCESS = 'FETCH_REDDIT_POSTS_SUCCESS';
export const FETCH_REDDIT_POSTS_FAILURE = 'FETCH_REDDIT_POSTS_FAILURE';
